# Generated by Django 5.2.7 on 2025-10-28 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='flowgroup',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.familymember'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PARENT', 'Parent'), ('CHILD', 'Child')], default='PARENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
