# Generated by Django 5.2.7 on 2025-10-29 17:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_transaction_options_flowgroup_is_shared_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={},
        ),
        migrations.AlterModelOptions(
            name='flowgroup',
            options={'ordering': ['group_type', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['order', '-date']},
        ),
        migrations.AlterUniqueTogether(
            name='flowgroup',
            unique_together={('family', 'name')},
        ),
        migrations.AddField(
            model_name='flowgroup',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='familyconfiguration',
            name='base_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='familyconfiguration',
            name='closing_day',
            field=models.PositiveSmallIntegerField(default=5, help_text='Day of the month (1-31) that defines the cycle closure.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='familyconfiguration',
            name='period_type',
            field=models.CharField(choices=[('M', 'Monthly'), ('B', 'Bi-weekly'), ('W', 'Weekly')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='flowgroup',
            name='group_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE_MAIN', 'Main Expense (Essential)'), ('EXPENSE_SECONDARY', 'Secondary Expense (Non-Essential)')], default='EXPENSE_MAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='flowgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flowgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_flow_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.RemoveField(
            model_name='flowgroup',
            name='is_shared',
        ),
    ]
