# Generated by Django 5.2.7 on 2025-10-29 20:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_familymember_options_alter_flowgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transaction',
            name='realized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familyconfiguration',
            name='closing_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='familyconfiguration',
            name='family',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='finances.family'),
        ),
        migrations.AlterField(
            model_name='familyconfiguration',
            name='period_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Cycle'), ('BIWEEKLY', 'Bi-Weekly Cycle')], default='MONTHLY', max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PARENT', 'Parent'), ('CHILD', 'Child')], default='CHILD', max_length=10),
        ),
        migrations.AlterField(
            model_name='flowgroup',
            name='group_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE_MAIN', 'Main Expense (e.g., Rent, Bills)'), ('EXPENSE_SECONDARY', 'Secondary Expense (e.g., Groceries, Entertainment)')], default='EXPENSE_SECONDARY', max_length=20),
        ),
        migrations.AlterField(
            model_name='flowgroup',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='flowgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
