# Generated by Django 5.2.7 on 2025-10-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_remove_transaction_realized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='realized',
            field=models.BooleanField(default=False),
        ),
    ]
