# Generated by Django 5.2.7 on 2025-10-30 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_transaction_realized'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='flowgroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='investment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='familyconfiguration',
            name='closing_day',
            field=models.IntegerField(default=1, help_text='Day of the month for monthly cycle closure (1-31).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='familyconfiguration',
            name='period_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Cycle'), ('BI_WEEKLY', 'Bi-Weekly Cycle')], default='MONTHLY', max_length=10),
        ),
        migrations.AlterField(
            model_name='flowgroup',
            name='group_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE_MAIN', 'Main Expense'), ('EXPENSE_SECONDARY', 'Secondary Expense')], default='EXPENSE_MAIN', max_length=20),
        ),
        migrations.RemoveField(
            model_name='flowgroup',
            name='order',
        ),
    ]
