# Generated by Django 5.2.7 on 2025-10-29 21:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_familymember_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='realized',
        ),
        migrations.AlterField(
            model_name='familyconfiguration',
            name='closing_day',
            field=models.PositiveSmallIntegerField(default=5, help_text='Day of the month (1-31) that defines the cycle closure.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='familyconfiguration',
            name='family',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='finances.family'),
        ),
        migrations.AlterField(
            model_name='familyconfiguration',
            name='period_type',
            field=models.CharField(choices=[('M', 'Monthly'), ('B', 'Bi-weekly'), ('W', 'Weekly')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PARENT', 'Parent'), ('CHILD', 'Child')], default='PARENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='flowgroup',
            name='group_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE_MAIN', 'Main Expense (Essential)'), ('EXPENSE_SECONDARY', 'Secondary Expense (Non-Essential)')], default='EXPENSE_MAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='flowgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flowgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_flow_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('user', 'family')},
        ),
    ]
