# Generated by Django 5.2.7 on 2025-10-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_alter_flowgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
