# Generated by Django 5.2.7 on 2025-10-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_alter_investment_date_created'),
        ('finances', '0009_migration_add_realized'),
    ]

    operations = [
    ]
