# Generated by Django 5.2.7 on 2025-10-30 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_merge_20251030_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowgroup',
            options={'ordering': ['group_type', 'order', 'name']},
        ),
        migrations.RemoveField(
            model_name='investment',
            name='date_created',
        ),
        migrations.AddField(
            model_name='flowgroup',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='familyconfiguration',
            name='closing_day',
            field=models.PositiveSmallIntegerField(default=5, help_text='Day of the month (1-31) that defines the cycle closure.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='familyconfiguration',
            name='period_type',
            field=models.CharField(choices=[('M', 'Monthly'), ('B', 'Bi-weekly'), ('W', 'Weekly')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='flowgroup',
            name='group_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE_MAIN', 'Main Expense (Essential)'), ('EXPENSE_SECONDARY', 'Secondary Expense (Non-Essential)')], default='EXPENSE_MAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='realized',
            field=models.BooleanField(default=False, help_text='Whether this transaction has been consolidated/completed'),
        ),
        migrations.AlterUniqueTogether(
            name='flowgroup',
            unique_together={('family', 'name')},
        ),
    ]
