# Generated by Django 5.2.7 on 2025-10-31 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_alter_flowgroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyconfiguration',
            name='closing_day',
        ),
        migrations.AddField(
            model_name='familyconfiguration',
            name='starting_day',
            field=models.PositiveSmallIntegerField(default=5, help_text='Day of the month (1-31) that defines the cycle start.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
