# Generated by Django 5.2.7 on 2025-11-01 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_remove_familyconfiguration_closing_day_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flowgroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flowgroup',
            name='period_start_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Start date of the period this FlowGroup belongs to'),
        ),
        migrations.AlterUniqueTogether(
            name='flowgroup',
            unique_together={('family', 'name', 'period_start_date')},
        ),
    ]
