# Generated by Django 5.2.7 on 2025-11-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_alter_flowgroup_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowgroup',
            name='assigned_children',
            field=models.ManyToManyField(blank=True, help_text='Children who have access to this Kids group', limit_choices_to={'role': 'CHILD'}, related_name='kids_flow_groups', to='finances.familymember'),
        ),
        migrations.AddField(
            model_name='flowgroup',
            name='is_kids_group',
            field=models.BooleanField(default=False, help_text='If True, this is a Kids group and budget becomes income for assigned children'),
        ),
        migrations.AddField(
            model_name='flowgroup',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='If True, this group is visible and editable by all Parents and Admins'),
        ),
    ]
