# Generated by Django 5.2.7 on 2025-11-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_flowgroup_assigned_children_flowgroup_is_kids_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowgroup',
            name='assigned_members',
            field=models.ManyToManyField(blank=True, help_text='Parents and Admins who have access to this Shared group', limit_choices_to={'role__in': ['ADMIN', 'PARENT']}, related_name='shared_flow_groups', to='finances.familymember'),
        ),
    ]
