# Generated by Django 5.2.7 on 2025-11-04 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_flowgroup_assigned_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowgroup',
            name='realized',
            field=models.BooleanField(default=False, help_text='For Kids groups: marks if the budget has been given to the child (parents only)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_child_manual_income',
            field=models.BooleanField(default=False, help_text='True if this is a manual income entry by a CHILD user (not from Kids group budget)'),
        ),
        migrations.CreateModel(
            name='FamilyMemberRoleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_date', models.DateField(help_text='Start date of the period this role applies to')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('PARENT', 'Parent'), ('CHILD', 'Child')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_history', to='finances.familymember')),
            ],
            options={
                'ordering': ['-period_start_date'],
                'indexes': [models.Index(fields=['member', 'period_start_date'], name='finances_fa_member__3b7908_idx')],
                'unique_together': {('member', 'period_start_date')},
            },
        ),
    ]
