# Generated by Django 5.2.7 on 2025-11-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_flowgroup_realized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_child_expense',
            field=models.BooleanField(default=False, help_text='True if this is aan expenses added tpo a FlowGroup by a CHILD user)'),
        ),
    ]
