# Generated by Django 5.2.7 on 2025-11-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0017_transaction_is_child_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowgroup',
            name='is_investment',
            field=models.BooleanField(default=False, help_text='If True, realized amounts are added to investment balance and deducted from expense calculations'),
        ),
    ]
