# Generated by Django 5.2.7 on 2025-11-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0018_flowgroup_is_investment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the closed period')),
                ('end_date', models.DateField(help_text='End date of the closed period')),
                ('period_type', models.CharField(choices=[('M', 'Monthly'), ('B', 'Bi-weekly'), ('W', 'Weekly')], help_text='Type of period when it was closed', max_length=1)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_periods', to='finances.family')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('family', 'start_date')},
            },
        ),
    ]
