# Generated by Django 5.2.7 on 2025-11-11 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0019_closedperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of the bank account', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Current bank balance', max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Date of balance check')),
                ('period_start_date', models.DateField(help_text='Period this balance belongs to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_balances', to='finances.family')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_balances', to='finances.familymember')),
            ],
            options={
                'ordering': ['-date', 'member'],
            },
        ),
    ]
