# Generated by Django 5.2.7 on 2025-11-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0021_bankbalance_amount_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Current system version (e.g., 1.0.0, 1.0.0-alpha1, 1.0.0-beta1)', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Version',
                'verbose_name_plural': 'System Versions',
            },
        ),
    ]
