# Generated by Django 5.2.7 on 2025-11-14 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0023_closedperiod_base_currency_alter_bankbalance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyconfiguration',
            name='base_currency',
            field=models.CharField(default='USD', help_text='Base currency for the family (e.g., USD, BRL, EUR)', max_length=3),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the period')),
                ('end_date', models.DateField(help_text='End date of the period')),
                ('period_type', models.CharField(choices=[('M', 'Monthly'), ('B', 'Bi-weekly'), ('W', 'Weekly')], help_text='Type of period', max_length=1)),
                ('currency', models.CharField(default='USD', help_text='Currency for this period', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='finances.family')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('family', 'start_date')},
            },
        ),
        migrations.DeleteModel(
            name='ClosedPeriod',
        ),
    ]
