# Generated by Django 5.2.7 on 2025-11-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0025_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkippedUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version that was skipped (e.g., 1.0.0-alpha5)', max_length=50, unique=True)),
                ('skipped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skipped Update',
                'verbose_name_plural': 'Skipped Updates',
                'ordering': ['-skipped_at'],
            },
        ),
    ]
