# Generated by Django 5.2.7 on 2025-11-19 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0027_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyconfiguration',
            name='bank_reconciliation_tolerance',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Percentage tolerance for bank reconciliation discrepancy warnings (e.g., 5.00 for 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
