# Generated by Django 5.2.7 on 2025-11-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0028_familyconfiguration_bank_reconciliation_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(
                choices=[('en', 'English'), ('pt-br', 'Português (Brasil)')],
                default='en',
                help_text="User's preferred language",
                max_length=10
            ),
        ),
    ]
