# Generated by Django 5.2.7 on 2025-12-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0029_customuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowgroup',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='If True, this group and its fixed transactions will be copied to new periods'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_fixed',
            field=models.BooleanField(default=False, help_text='If True, this transaction will be auto-copied to new periods'),
        ),
    ]
