# Generated by Django 5.2.7 on 2025-12-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0030_add_recurring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowgroup',
            name='closed',
            field=models.BooleanField(default=False, help_text='For credit card groups: marks if the bill has been closed and paid'),
        ),
        migrations.AddField(
            model_name='flowgroup',
            name='is_credit_card',
            field=models.BooleanField(default=False, help_text='If True, this is a credit card group with special billing cycle handling'),
        ),
    ]
