# Generated by Django 5.2.7 on 2025-12-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0031_flowgroup_closed_flowgroup_is_credit_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyconfiguration',
            name='bank_reconciliation_mode',
            field=models.CharField(choices=[('general', 'General'), ('detailed', 'Detailed')], default='general', help_text='Display mode for bank reconciliation: general (family total) or detailed (per user)', max_length=10),
        ),
    ]
