"""
Django settings for wimm_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@+@#^v(s25&0t6yvx5)tm$3!ug(f*thk==-_b4v=v7pieqk0z_'





# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    #My App
    'finances'
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Language detection and activation
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'finances.middleware.UserLanguageMiddleware',  # Per-user language preference
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'finances.middleware.SetupRequiredMiddleware',
]

ROOT_URLCONF = 'wimm_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # i18n context
                'finances.context_processors.database_version',
                'finances.context_processors.app_version',
                'finances.context_processors.demo_mode_processor',
                'finances.context_processors.user_role_processor',
                'finances.context_processors.notifications_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'wimm_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

ALLOWED_HOSTS = []
CSRF_TRUSTED_ORIGINS = []
DEBUG = False

EXTERNAL_SETTINGS_PATH = '/app/config/local_settings.py'

if os.path.exists(EXTERNAL_SETTINGS_PATH):
    print(f"*** Loading external settings ***")
    try:
        # Executes the code from the external file in the global context (overwriting the variables above)
        # The external file can redefine ALLOWED_HOSTS, DATABASES, CSRF_TRUSTED_ORIGINS, etc.
        #It means that SweetMoney is running from a container - Deployment mode
        exec(open(EXTERNAL_SETTINGS_PATH).read())
    except Exception as e:
        print(f"Critical error when loading external settings: {e}")


    DB_PATH = os.environ.get('DB_PATH', '/app/db/db.sqlite3')

    DEBUG = False

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            #Django will use this path in the Docker volume.
            'NAME': DB_PATH,
        }
    }

else:
    # SECURITY WARNING: don't run with debug turned on in production!
    print('Devel mode')
    DEBUG = True
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db/db.sqlite3',
        }
    }

    # Load local settings for development (email configuration, etc.)
    LOCAL_SETTINGS_PATH = BASE_DIR / 'config' / 'local_settings.py'
    if os.path.exists(LOCAL_SETTINGS_PATH):
        print(f"*** Loading local development settings from {LOCAL_SETTINGS_PATH} ***")
        try:
            exec(open(LOCAL_SETTINGS_PATH).read())
        except Exception as e:
            print(f"Error loading local settings: {e}")

# 1. Configura o seu modelo CustomUser como o modelo padrão de usuário
AUTH_USER_MODEL = 'finances.CustomUser'

# 2. Redireciona para o login se o usuário não estiver autenticado
LOGIN_URL = '/login/'

# 3. Redireciona para o Dashboard (página inicial) após o login
LOGIN_REDIRECT_URL = '/'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('pt-br', 'Português (Brasil)'),
]

# Path where translation files will be stored
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Deploy CFG
STATIC_ROOT = os.path.join(Path(__file__).resolve().parent.parent, 'staticfiles')

# Demo mode settings (defaults to False if not set in local_settings)
DEMO_MODE = False
DEMO_REPO_URL = ''

# Import local settings if available
# First try config/local_settings.py (Docker production setup)
# Then try wimm_project/local_settings.py (local development)
try:
    import sys
    config_path = BASE_DIR / 'config'
    if config_path.exists() and str(config_path) not in sys.path:
        sys.path.insert(0, str(config_path))
    from local_settings import *
except ImportError:
    try:
        from .local_settings import *
    except ImportError:
        pass

