"""
Django settings for wimm_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@+@#^v(s25&0t6yvx5)tm$3!ug(f*thk==-_b4v=v7pieqk0z_'





# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be first for async support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Third-party apps
    'channels',
    'csp',  # Content Security Policy
    'pwa',

    #My App
    'finances'
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',  # Content Security Policy
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Language detection and activation
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'finances.middleware.UserLanguageMiddleware',  # Per-user language preference
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'finances.middleware.SetupRequiredMiddleware',
]

ROOT_URLCONF = 'wimm_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # i18n context
                'finances.context_processors.database_version',
                'finances.context_processors.app_version',
                'finances.context_processors.demo_mode_processor',
                'finances.context_processors.user_role_processor',
                'finances.context_processors.is_dashboard_view',
                'finances.context_processors.notifications_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'wimm_project.wsgi.application'

# ASGI Application for WebSocket support
ASGI_APPLICATION = 'wimm_project.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Security settings (can be overridden in local_settings.py)
ALLOWED_HOSTS = []
CSRF_TRUSTED_ORIGINS = []
DEBUG = False

# ==================================================================
# Security Settings (Production)
# ==================================================================
# These settings are OPTIONAL and controlled via local_settings.py
# They are disabled by default to allow local development with IP/localhost

# SSL/HTTPS settings (only enable if you have HTTPS configured)
SECURE_SSL_REDIRECT = False  # Set True in local_settings.py if using HTTPS
SECURE_HSTS_SECONDS = 0  # Set to 31536000 (1 year) in production with HTTPS
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# Security headers (safe to enable even without HTTPS)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking

# Cookie security (only enable with HTTPS in production)
SESSION_COOKIE_SECURE = False  # Set True in local_settings.py if using HTTPS
CSRF_COOKIE_SECURE = False  # Set True in local_settings.py if using HTTPS
SESSION_COOKIE_HTTPONLY = True  # Safe to enable always
CSRF_COOKIE_HTTPONLY = False  # Must be False for JavaScript access

# Session security
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
CSRF_COOKIE_SAMESITE = 'Lax'

# ==================================================================
# WebSocket Security Settings (Optional)
# ==================================================================
# These can be overridden in local_settings.py

# WebSocket rate limiting
WS_RATE_LIMIT_MAX_ATTEMPTS = 10  # Max connection attempts per user
WS_RATE_LIMIT_WINDOW_SECONDS = 60  # Time window in seconds

# WebSocket connection timeout
WS_CONNECTION_TIMEOUT = 3600  # 1 hour - disconnect idle connections
WS_HEARTBEAT_INTERVAL = 30  # Heartbeat check interval in seconds

# ==================================================================
# Content Security Policy (CSP) Settings
# ==================================================================
# These can be overridden in local_settings.py
# CSP helps prevent XSS, clickjacking, and other code injection attacks

# Report-only mode (recommended for initial deployment)
# Set to False in local_settings.py to enforce CSP
CSP_REPORT_ONLY = True

# Default source for all content types
CSP_DEFAULT_SRC = ("'self'",)

# Script sources (JavaScript)
CSP_SCRIPT_SRC = (
    "'self'",
    "cdn.jsdelivr.net",  # Used for external libraries
    "'unsafe-inline'",  # Allow inline scripts (consider removing after audit)
)

# Style sources (CSS)
CSP_STYLE_SRC = (
    "'self'",
    "cdn.jsdelivr.net",
    "'unsafe-inline'",  # Required for inline styles
)

# Image sources
CSP_IMG_SRC = (
    "'self'",
    "data:",  # Allow data: URIs for images
)

# Font sources
CSP_FONT_SRC = (
    "'self'",
    "cdn.jsdelivr.net",
)

# Connection sources (AJAX, WebSocket, etc.)
# Will be configured in local_settings.py based on domain
CSP_CONNECT_SRC = ("'self'",)

# Frame sources (iframes)
CSP_FRAME_SRC = ("'none'",)

# Object sources (Flash, etc.)
CSP_OBJECT_SRC = ("'none'",)

# Base URI for relative URLs
CSP_BASE_URI = ("'self'",)

# Form action targets
CSP_FORM_ACTION = ("'self'",)

# Frame ancestors (who can embed this page)
CSP_FRAME_ANCESTORS = ("'none'",)

# Upgrade insecure requests (HTTP to HTTPS)
# Only enable if using HTTPS
CSP_UPGRADE_INSECURE_REQUESTS = False

EXTERNAL_SETTINGS_PATH = '/app/config/local_settings.py'

if os.path.exists(EXTERNAL_SETTINGS_PATH):
    print(f"*** Loading external settings ***")
    try:
        # Executes the code from the external file in the global context (overwriting the variables above)
        # The external file can redefine ALLOWED_HOSTS, DATABASES, CSRF_TRUSTED_ORIGINS, etc.
        #It means that SweetMoney is running from a container - Deployment mode
        exec(open(EXTERNAL_SETTINGS_PATH).read())
    except Exception as e:
        print(f"Critical error when loading external settings: {e}")


    DB_PATH = os.environ.get('DB_PATH', '/app/db/db.sqlite3')

    DEBUG = False

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            #Django will use this path in the Docker volume.
            'NAME': DB_PATH,
            'OPTIONS': {
                'timeout': 20,  # Aumentar timeout de 5s (padrão) para 20s
                'init_command': 'PRAGMA journal_mode=WAL;',  # Write-Ahead Logging para melhor concorrência
            },
        }
    }

else:
    # SECURITY WARNING: don't run with debug turned on in production!
    print('Devel mode')
    DEBUG = True
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db/db.sqlite3',
            'OPTIONS': {
                'timeout': 20,  # Aumentar timeout de 5s (padrão) para 20s
                'init_command': 'PRAGMA journal_mode=WAL;',  # Write-Ahead Logging para melhor concorrência
            },
        }
    }

    # Load local settings for development (email configuration, etc.)
    LOCAL_SETTINGS_PATH = BASE_DIR / 'config' / 'local_settings.py'
    if os.path.exists(LOCAL_SETTINGS_PATH):
        print(f"*** Loading local development settings from {LOCAL_SETTINGS_PATH} ***")
        try:
            exec(open(LOCAL_SETTINGS_PATH).read())
        except Exception as e:
            print(f"Error loading local settings: {e}")

# 1. Configura o seu modelo CustomUser como o modelo padrão de usuário
AUTH_USER_MODEL = 'finances.CustomUser'

# 2. Redireciona para o login se o usuário não estiver autenticado
LOGIN_URL = '/login/'

# 3. Redireciona para o Dashboard (página inicial) após o login
LOGIN_REDIRECT_URL = '/'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('pt-br', 'Português (Brasil)'),
]

# Path where translation files will be stored
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Deploy CFG
STATIC_ROOT = os.path.join(Path(__file__).resolve().parent.parent, 'staticfiles')

# Demo mode settings (defaults to False if not set in local_settings)
DEMO_MODE = False
DEMO_REPO_URL = ''

# Import local settings if available
# First try config/local_settings.py (Docker production setup)
# Then try wimm_project/local_settings.py (local development)
try:
    import sys
    config_path = BASE_DIR / 'config'
    if config_path.exists() and str(config_path) not in sys.path:
        sys.path.insert(0, str(config_path))
    from local_settings import *
except ImportError:
    try:
        from .local_settings import *
    except ImportError:
        pass


# =====================================================
# Progressive Web App (PWA) Configuration
# =====================================================

PWA_APP_NAME = 'SweetMoney'
PWA_APP_DESCRIPTION = 'Family-oriented personal finance management'
PWA_APP_THEME_COLOR = '#10b981'  # Green - matches SweetMoney branding
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'  # Opens app without browser chrome
PWA_APP_START_URL = '/'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_LANG = 'en-US'
PWA_APP_DIR = 'ltr'

# PWA Icons Configuration
PWA_APP_ICONS = [
    {
        'src': '/static/finances/images/favicons/android-chrome-192x192.png',
        'sizes': '192x192',
        'type': 'image/png',
        'purpose': 'any'
    },
    {
        'src': '/static/finances/images/favicons/android-chrome-512x512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any'
    }
]

# PWA Icons for Apple/iOS
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/finances/images/favicons/apple-touch-icon.png',
        'sizes': '180x180'
    }
]

# Service Worker Configuration - handled by custom views
# PWA_SERVICE_WORKER_PATH is not needed as we use custom template-based service worker


# =====================================================
# Django Channels Configuration for Real-time Updates
# =====================================================

# Channel Layers Configuration for Redis
# Build Redis URL with optional password
redis_password = os.environ.get('REDIS_PASSWORD', None)
# Strip whitespace and treat empty string as None
if redis_password is not None:
    redis_password = redis_password.strip()
    if not redis_password:  # Empty string after stripping
        redis_password = None

redis_host = os.environ.get('REDIS_HOST', '127.0.0.1')
redis_port = os.environ.get('REDIS_PORT', '6379')

# Debug: Log Redis configuration (will help diagnose connection issues)
print(f"[Django Channels] Redis configuration:")
print(f"  - Host: {redis_host}")
print(f"  - Port: {redis_port}")
print(f"  - Password: {'SET ({} chars)'.format(len(redis_password)) if redis_password else 'NOT SET'}")

# Check if we should use InMemoryChannelLayer (development without Redis)
use_in_memory = os.environ.get('USE_REDIS_MOCK', '').lower() == 'true'

# Auto-detect Redis availability in development
if DEBUG and not use_in_memory:
    import socket
    try:
        # Try to connect to Redis to check if it's available
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(1)
        sock.connect((redis_host, int(redis_port)))
        sock.close()
        redis_available = True
    except (socket.error, socket.timeout, ValueError):
        redis_available = False
        print(f"[Django Channels] Redis not available at {redis_host}:{redis_port}, using InMemoryChannelLayer")
else:
    redis_available = not use_in_memory

# Configure channel layer based on Redis availability
if redis_available:
    # Use Redis for production or when Redis is available in development
    if redis_password:
        # Format: redis://:password@host:port
        redis_url = f"redis://:{redis_password}@{redis_host}:{redis_port}"
    else:
        # Format: redis://host:port (no password)
        redis_url = f"redis://{redis_host}:{redis_port}"

    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [redis_url],
                "capacity": 1500,  # Max messages per channel
                "expiry": 10,  # Message expiry in seconds
            },
        },
    }
    print(f"[Django Channels] Using Redis channel layer at {redis_host}:{redis_port}")
else:
    # Use in-memory layer for development when Redis is not available
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        }
    }
    print("[Django Channels] Using InMemoryChannelLayer (development mode without Redis)")
